#!/usr/bin/env bash

########################################################################
# testheapimp
# Author: Bob Dondero
########################################################################

# Perform timing tests of the testheapmgr program whose name is %1.
# %1 must be an executable file that already exists.

# Validate the argument.
if [ "$#" -ne "1" ]; then
   echo "Usage: testheapimp executablefile"
   exit 1
fi

# Capture the argument.
executablefile=$1

echo "==============================================================="
$executablefile RandomRandom 100000 2000
$executablefile Worst 100000 2000
echo "---------------------------------------------------------------"
$executablefile RandomRandom 100000 20000
$executablefile Worst 100000 20000
